name: Testing CI
on: [push]
jobs:
  Unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install
        run: npm ci

      - name: Run unit and integration test
        run: |
          npm run test

  # E2E-tests:
  #   runs-on: ubuntu-latest
  #   container: node:latest
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Connect to PostgreSQL
  #       run: npm run ci:test
  #       env:
  #         DB_USER: postgres
  #         DB_PASSWORD: postgres
  #         DB_HOST: postgres
  #         DB_NAME: postgres
  #         DB_PORT: 5432

  #     - name: Run E2E tests
  #       run: |
  #         npm run test:e2e
  #       env:
  #         DB_USER: postgres
  #         DB_PASSWORD: postgres
  #         DB_HOST: postgres
  #         DB_NAME: postgres
  #         DB_PORT: 5432
  #         JWT_SECRET: 7fDzByet5vMSlZRWUOG8NaXFgYn9JI31
  #         JWT_RECOVERY_SECRET: 7fDzByet5vMSlZRWUOG8NaXFgYn9JI31
  #         RECOVERY_SERVICE_HOST: smtp.gmail.com